version: '3'
services:
  elasticsearch:
    hostname: elasticsearch
    image: elasticsearch:5.5.0
    volumes:
      - ./elasticsearch/volumes/config:/usr/share/elasticsearch/config
      - ./elasticsearch/volumes/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200/tcp
      - 9300:9300/tcp
  logstash:
    command: -f /etc/logstash/conf.d/logstash.conf
    hostname: logstash
    image: logstash:5.5.0
    links:
      - elasticsearch
    volumes:
      - ./logstash/volumes/config:/etc/logstash/conf.d
  kibana:
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    hostname: kibana
    image: kibana:5.5.0
    links:
      - elasticsearch
    ports:
      - 5601:5601/tcp
